version: '3.9'

networks:
   somenetweork:
    driver: bridge

services:
 homeworkotus:
  image: ${DOCKER_REGISTRY-}homeworkotus
  container_name: otuswebapicont
  build:
   context: .
   dockerfile: /HomeWorkOTUS/Dockerfile
  ports:
   - '55555:8081'
  networks:
   - somenetweork
  depends_on:
   - postgres_db
   - rabbitmq

 postgres_db:
  image: postgres:latest
  container_name: pgmaster
  environment:
   - POSTGRES_DB=otusdb
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=pass
  ports:
   - '5432:5432'
  networks:
   - somenetweork

 rabbitmq:
    image: rabbitmq:3.10.7-management
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=pass
    ports:
      - 15672:15672
      - 5672:5672 
    networks:
      - somenetweork

 redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=pass
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    networks:
      - somenetweork


 # postgres_slave1:
 #  image: postgres:latest
 #  container_name: pgslave1
 #  environment:
 #   - POSTGRES_DB=otusdb
 #   - POSTGRES_USER=postgres
 #   - POSTGRES_PASSWORD=pass
 #  ports:
 #   - '15432:5432'
 #  networks:
 #   - somenetweork

 # postgres_slave2:
 #  image: postgres:latest
 #  container_name: pgslave2
 #  environment:
 #   - POSTGRES_DB=otusdb
 #   - POSTGRES_USER=postgres
 #   - POSTGRES_PASSWORD=pass
 #  ports:
 #   - '25432:5432'
 #  networks:
 #   - somenetweork